#!/bin/sh
if [ -f /media/data/apps/emulationstation.opk ]; then
    # start EmulationStation as default launcher
    /usr/bin/opkrun /media/data/apps/emulationstation.opk
    # when emulationstation quits -> we start gmenu2x
    /usr/bin/gmenu2x

elif [ -f /media/data/apps/gmenunx.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/data/apps/gmenunx.opk
else
    /usr/bin/gmenu2x
fi
